# Generated by Django 3.2 on 2021-08-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
